---
title: "init_analysis"
author: "Chao Pang, Krihsna Kalluri"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(maps)
library(mapdata)
library(choroplethr)
```

```{r}
setwd('..')
folder_path <- paste(getwd(), 'data', sep='/')
all_breweries <- read_csv(paste(folder_path, 'all_breweries.csv', sep='/'))
all_beers <- read_csv(paste(folder_path, 'all_beers.csv', sep='/'))
```

Clean up the data

Below we cleaned up the beer_abv column by removing the characters % ABV.

```{r}
clean_up_beer_style <- function(beer_style_name){
  if (beer_style_name == "IPA - Imperial / Double New England / Hazy"){
    return ("Double New England IPA")
  } else if (beer_style_name == "Red Ale - American Amber / Red"){
    return ("Red American Amber")
  } else if (beer_style_name == "IPA - New England / Hazy"){
    return ("New England IPA")
  } else if (beer_style_name == "IPA - Imperial / Double"){
    return ("Double IPA")
  } else if (beer_style_name == "Farmhouse Ale - Saison"){
    return ("Farmhouse Ale")
  } else if (beer_style_name == "Stout - Imperial / Double"){
    return ("Imperial Stout")
  }
  
  return (beer_style_name)
}
```

```{r}
cleaned_all_beers <- all_beers %>% 
  mutate(beer_abv=as.double(str_trim(gsub("%\\s+ABV", "", beer_abv)))) %>%
  mutate(beer_ibu=as.double(str_trim(gsub("\\s+IBU", "", beer_ibu)))) %>%
  mutate(beer_added=as.Date(beer_added, format = "%m/%d/%y")) %>%
  mutate(year=format(beer_added, format="%Y")) %>%
  mutate(beer_style=sapply(beer_style, clean_up_beer_style))
```

```{r}
top_most_popular_beer_styles <- cleaned_all_beers %>%
  drop_na(beer_average_rating) %>%
  group_by(beer_style) %>%
  summarise(freq=n(), style_average_rating=mean(beer_average_rating)) %>%
  ungroup() %>%
  arrange(desc(freq)) %>%
  mutate(rn=row_number()) %>%
  filter(rn <= 20) %>%
  mutate(beer_style=fct_reorder(factor(beer_style), rn))

ggplot(top_most_popular_beer_styles, aes(x=freq, y=fct_reorder(beer_style, freq))) +
  geom_point() + 
  ggtitle("Top 20 most popular beer styles") + 
  xlab("Num of beers") + 
  ylab("Beer style")
```

```{r}
most_popular_beer_ratings <- top_most_popular_beer_styles %>% 
  inner_join(cleaned_all_beers, on = beer_style) %>%
  drop_na(beer_average_rating)
  
ggplot(most_popular_beer_ratings, aes(x=beer_average_rating, y= fct_reorder(beer_style, beer_average_rating))) +
  geom_boxplot() + 
  ggtitle("Boxplots of beer ratings for the top 20 most popular beer styles") + 
  xlab("Beer rating") + 
  ylab("Beer style")
```

```{r}
cleaned_all_beers %>%
  drop_na(c(beer_num_ratings, beer_average_rating)) %>%
  inner_join(top_most_popular_beer_styles, on=beer_style) %>%
  
ggplot(aes(x=beer_num_ratings, y=beer_average_rating)) +
  geom_point(alpha=0.2)
```

```{r}
pairs(cleaned_all_beers %>%
  filter(beer_abv <= 20) %>%
  filter(beer_ibu <= 400) %>%
  select(c(beer_abv, beer_ibu, beer_average_rating, beer_num_ratings)) %>%
  drop_na())
```

```{r}
facted_hist_input <- cleaned_all_beers %>% 
  inner_join(top_most_popular_beer_styles, on=beer_style) %>%
  drop_na(c(beer_average_rating, year)) %>%
  select(beer_style, beer_added, year, rn) %>%
  mutate(year=as.double(year)) %>%
  mutate(beer_style=factor(beer_style))
  
ggplot(facted_hist_input, aes(year)) + 
  geom_bar()  + 
  facet_wrap(~fct_reorder(facted_hist_input$beer_style, facted_hist_input$rn))
```

```{r}
parallel_coord_input <- most_popular_beer_ratings %>%
  select(beer_style, beer_abv, beer_ibu, beer_average_rating, beer_num_ratings, year) %>%
  mutate(year=as.integer(year)) %>%
  drop_na() %>% 
  filter(beer_abv <= 20) %>%
  filter(beer_ibu <= 400)
  

GGally::ggparcoord(parallel_coord_input, 
                   columns=2:5, 
                   scale='uniminmax', 
                   alphaLines = 0.2, 
                   groupColumn = 1)
```

```{r}
weighted_average_rating_by_state <- cleaned_all_breweries %>%
  select(brewery_id, num_of_ratings, num_of_beers, average_rating, state) %>%
  unique() %>%
  group_by(state) %>%
  summarise(weighted_average_rating=num_of_beers/sum(num_of_beers) * average_rating,
            average_rating = average_rating) %>%
  summarise(weighted_average_rating=sum(weighted_average_rating), 
            average_rating=mean(average_rating),
            total_num_of_breweries = n())

ggplot(weighted_average_rating_by_state, aes(weighted_average_rating, average_rating)) +
  geom_point()
```

```{r}
cleaned_all_breweries <- all_breweries %>%
  filter(num_of_beers >= 10) %>%
  filter(!brewery_type %in% c("proprietor", "bar", "nano", "closed"))
```

```{r}
cleaned_all_breweries %>%
  group_by(state) %>%
  summarise(freq=n(), 
            state_mean_rating=mean(average_rating), 
            state_median_rating=median(average_rating), 
            state_mean_num_of_ratings=mean(num_of_ratings), 
            state_median_num_of_ratings=median(num_of_ratings)) %>%
  ungroup() %>%
  
  ggplot(aes(state_mean_rating, state_mean_num_of_ratings)) +
    geom_point()
```

```{r}
cleaned_all_breweries %>%
  group_by(state) %>%
  arrange(desc(average_rating)) %>%
  slice(1:2) %>%
  ungroup() %>%
  
ggplot(aes(x=average_rating, y=fct_reorder(state, average_rating, .fun=max))) +
  geom_point()
```

```{r}
population <- read_csv(paste(folder_path, 'us_population_by_state_2020.csv', sep='/')) %>%
  rename(state=US_States)
population
```

```{r}
weighted_average_rating_by_state %>% 
  left_join(population, by=c("state")) %>%
ggplot(aes(total_num_of_breweries, Population_2020)) +
  geom_point()
```

### Geoplot

```{r}
coordinate_all_breweries <- cleaned_all_breweries %>%
  filter(!is.na(longitude) | !is.na(latitude)) %>%
  filter(!state %in% c('Alaska', 'Hawaii'))
```

```{r}
usa <- map_data('state')
ggplot() +
  geom_polygon(data = usa,
               aes(
                 x = long,
                 y = lat,
                 group = group,
                 color = 'white'
               )) +
  geom_point(
    data = coordinate_all_breweries,
    aes(x = longitude, y = latitude),
    color = "red",
    alpha = 0.1
  ) +
  guides(fill = "none") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  ggtitle('U.S. Map') +
  coord_fixed(1.3)
```

```{r}
# data frame must contain "region" and "value" columns
df_brewery_count <-
  cleaned_all_breweries %>% group_by(state) %>% summarise(no_of_breweries = n()) %>%
  transmute(region = tolower(`state`), value = no_of_breweries)

state_choropleth(df_brewery_count,
                 title = "No of Breweries per State in 2021",
                 legend = "count")
```

```{r}
cleaned_all_breweries %>% 
  select(brewery_id, state, average_rating, num_of_beers, num_of_ratings) %>%
  unique() %>%
  arrange(desc(average_rating))

top_20_beers_average_rating <- cleaned_all_beers %>%
  group_by(brewery) %>%
  summarise(top_beer_average_rating=mean(beer_average_rating)) %>%
  drop_na()

popular_breweries_by_state <- cleaned_all_breweries %>%
  inner_join(top_20_beers_average_rating, on='brewery') %>%
  select(brewery_id, state, average_rating, num_of_beers, num_of_ratings, top_beer_average_rating) %>%
  unique() %>%
  drop_na(average_rating) %>%
  arrange(desc(average_rating)) %>%
  slice(1:100) %>%
  group_by(state) %>%
  summarise(average_rating=num_of_beers * average_rating / sum(num_of_beers)) %>%
  summarise(num=n(), state_average_rating=sum(average_rating)) %>%
  arrange(desc(num)) %>%
  ungroup() %>%
  transmute(region=tolower(state), value=num)

state_choropleth(popular_breweries_by_state,
                 title = "No of Breweries per State in 2021",
                 legend = "count")
```

```{r}
top_most_popular_beer_styles
```

```{r}
top_5_beers_produced_each_state <- cleaned_all_beers %>%
  group_by(state, beer_style) %>%
  summarise(no_of_beers = n()) %>%
  arrange(desc(no_of_beers)) %>%
  slice(1:5)
top_5_beers_produced_each_state
```

```{r}
us_temperatures <- read_csv(paste(folder_path, 'us_avg_temperature_by_state.csv', sep='/'))
us_temperatures
```

```{r}
temperature_top_5_beers <- top_5_beers_produced_each_state %>% left_join(y=us_temperatures, by=c("state"))
temperature_top_5_beers
```

```{r}
ggplot(temperature_top_5_beers, aes(fahrenheit_avg, state)) + 
  geom_point(aes(color = beer_style))
```

```{r}
new_england_by_state <- most_popular_beer_ratings %>%
  filter(beer_style %in% c("New England IPA", "Double New England IPA")) %>%
  group_by(state) %>%
  summarise(freq=n()) %>%
  transmute(region=tolower(gsub('[_]', ' ', state)), value=freq)

state_choropleth(new_england_by_state,
                 num_colors = 1,
                 title = "No of Breweries per State in 2021",
                 legend = "count")
```

```{r}
new_england_by_state <- most_popular_beer_ratings %>%
  filter(grepl('Sour', beer_style)) %>%
  group_by(state) %>%
  summarise(freq=n()) %>%
  transmute(region=tolower(gsub('[_]', ' ', state)), value=freq)

state_choropleth(new_england_by_state,
                 num_colors = 1,
                 title = "No of Breweries per State in 2021",
                 legend = "count")
```

```{r, fig.height=8, fig.width=10}
most_popular_beer_ratings %>%
  filter(rn <= 10) %>%
  mutate(state=gsub('[_]', ' ', state)) %>%
  group_by(state, beer_style) %>%
  summarise(freq=n(), rn=min(rn)) %>%
  mutate(freq=scale(freq)) %>%

ggplot(aes(fct_reorder(beer_style, rn), fct_rev(fct_infreq(state)), fill=freq)) +
  geom_tile(color="white") + 
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black")
  ) + 
  scale_x_discrete(labels = abbreviate)
```

```{r}
library("tmap")
library("tmaptools")
library("sf")
library("leaflet")
library("tigris")
#devtools::install_github('walkerke/tigris')
us_geo <- states(class = "sf")
```

```{r}
state_avg_rating <- cleaned_all_breweries %>%
  group_by(state) %>%
  summarise(BreweryCount= n(),
            AverageRating = mean(average_rating)) %>%
  rename(NAME = state)
```

```{r}

mean_rating_map <- inner_join(us_geo, state_avg_rating) %>% select(NAME, AverageRating, BreweryCount,  geometry)

mean_rating_map <- subset(mean_rating_map, !(NAME %in% c("Alaska", "Hawaii", "Puerto Rico")))

tmap_mode("view")

my_interactive_map <- tm_shape(mean_rating_map) +
  tm_polygons("BreweryCount", popup.vars=c(
                    "No Of Breweries in state: "="BreweryCount",
                    "Average Ratings in State: " = "AverageRating"), id = "NAME", border.col = "white",
              palette="Greens")

my_interactive_map <- tmap_leaflet(my_interactive_map)
#library(htmlwidgets)
#saveWidget(my_interactive_map, "state_avg_rating.html")
my_interactive_map
```
