# Interactive component

The purpose of this D3 visualization is to better understand the landscape of the craft beer industry. Specifically this visualization is primarily motivated by several questions shown below,

-   What are the popular beer styles?

-   What beer styles are more popular across different states?

-   What are the characteristics of each beer style?

-   why are certain beer styles better rated than others?

The D3 visualization combines several plots together including the beer style rating density, beer style popularity over time, beer ibu density, beer abv density, and beer style production by state. Although some of the plots have been shown individual in the results section of our book, we believe looking at the data holistically could give us a better understanding of the data. To avoid overplotting, we've only included the top 20 most popular beer styles in this visualization, which is defined as the number of beers associated with that particular beer style. Unfortunately, the D3 visualization is getting cut off after being rendered in the book, one would have to scroll up and down like crazy to see it. Therefore we decided to move the D3 visualization to vizhub, which can be found at <https://vizhub.com/ChaoPang/aa1efcb807334bf5b716f2a5a0c5c3a7?mode=full>

One of the things that we couldn't see previously in the results section is that we could look at the beer landscape as a whole. Specifically, we could see the differences in terms of the beer ABV and beer IBU among all the beer styles (after checking all beer styles). For instance, Sour styles have low IBU and ABV, however, these styles are highly rated by people. Another interesting observation is that the Märzen beer style follows a seasonal pattern shown in the Beer Style Popularity plot in the top right, honestly, we never heard of this style before and had to look it up, it turned out this is a October Festival beer, which is why we only observe it at the end of each year.

The rating slider is added with the intention to investigate what makes a highly rated beer for specific styles. Say let's find out what makes a good imperial stout and a bad imperial stout. If you select Imperial Stout and adjust the rating slider to 2-3.5, the beer abv shows a bi-modal distribution with two peaks around 20 and 35, this is what a bad Imperial Stout looks like. Now let's adjust the rating slider to 4-5, the beer abv now follows a uni-modal distribution with a slightly right skewness, and its peak centers around 50, this is what a good Imperial Stout looks like. The point here is that by adjust the beer rating, we could compare the distributions of the beer characteristics between good and bad beers for a specific beer style.

Finally let's explore where the highly rated beers are located across the countries. To do that, we need to select all beer styles and adjust the rating slider to 4-5. Let's scroll down to the Beer style by state plot. Vertically it shows California, Pennsylvania, Colorado, and New York are the leading states that make the most highly rated beers across different all styles. Horizontally, the highly rated New England IPA, Double IPA, and Imperial Stout beers are brewed by many states as well.
