---
title: "init_analysis"
author: "Chao Pang, Krihsna Kalluri"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(maps)
library(mapdata)
library(choroplethr)
```

```{r}
folder_path <- paste(getwd(), 'data', sep='/')
all_breweries <- read_csv(paste(folder_path, 'all_breweries.csv', sep='/'))
all_beers <- read_csv(paste(folder_path, 'all_beers.csv', sep='/'))
```

Clean up the data

Below we cleaned up the beer_abv column by removing the characters % ABV.

```{r}
clean_up_beer_style <- function(beer_style_name){
  if (beer_style_name == "IPA - Imperial / Double New England / Hazy"){
    return ("Double New England IPA")
  } else if (beer_style_name == "Red Ale - American Amber / Red"){
    return ("Red American Amber")
  } else if (beer_style_name == "IPA - New England / Hazy"){
    return ("New England IPA")
  } else if (beer_style_name == "IPA - Imperial / Double"){
    return ("Double IPA")
  } else if (beer_style_name == "Farmhouse Ale - Saison"){
    return ("Farmhouse Ale")
  } else if (beer_style_name == "Stout - Imperial / Double"){
    return ("Imperial Stout")
  }
  
  return (beer_style_name)
}
```

```{r}
cleaned_all_beers <- all_beers %>% 
  mutate(beer_abv=as.double(str_trim(gsub("%\\s+ABV", "", beer_abv)))) %>%
  mutate(beer_ibu=as.double(str_trim(gsub("\\s+IBU", "", beer_ibu)))) %>%
  mutate(beer_added=as.Date(beer_added, format = "%m/%d/%y")) %>%
  mutate(year=format(beer_added, format="%Y")) %>%
  mutate(beer_style=sapply(beer_style, clean_up_beer_style))
```

```{r}
top_most_popular_beer_styles <- cleaned_all_beers %>%
  drop_na(beer_average_rating) %>%
  group_by(beer_style) %>%
  summarise(freq=n(), style_average_rating=mean(beer_average_rating)) %>%
  ungroup() %>%
  arrange(desc(freq)) %>%
  mutate(rn=row_number()) %>%
  filter(rn <= 20) %>%
  mutate(beer_style=fct_reorder(factor(beer_style), rn))

ggplot(top_most_popular_beer_styles, aes(x=freq, y=fct_reorder(beer_style, freq))) +
  geom_point() + 
  ggtitle("Top 20 most popular beer styles") + 
  xlab("Num of beers") + 
  ylab("Beer style")
```

```{r}
most_popular_beer_ratings <- top_most_popular_beer_styles %>% 
  inner_join(cleaned_all_beers, on = beer_style) %>%
  drop_na(beer_average_rating)
  
ggplot(most_popular_beer_ratings, aes(x=beer_average_rating, y= fct_reorder(beer_style, beer_average_rating))) +
  geom_boxplot() + 
  ggtitle("Boxplots of beer ratings for the top 20 most popular beer styles") + 
  xlab("Beer rating") + 
  ylab("Beer style")
```

```{r}
cleaned_all_beers %>%
  drop_na(c(beer_num_ratings, beer_average_rating)) %>%
  inner_join(top_most_popular_beer_styles, on=beer_style) %>%
  
ggplot(aes(x=beer_num_ratings, y=beer_average_rating)) +
  geom_point(alpha=0.2)
```

```{r}
pairs(cleaned_all_beers %>%
  filter(beer_abv <= 20) %>%
  filter(beer_ibu <= 400) %>%
  select(c(beer_abv, beer_ibu, beer_average_rating, beer_num_ratings)) %>%
  drop_na())
```

```{r}
facted_hist_input <- cleaned_all_beers %>% 
  inner_join(top_most_popular_beer_styles, on=beer_style) %>%
  drop_na(c(beer_average_rating, year)) %>%
  select(beer_style, beer_added, year, rn) %>%
  mutate(year=as.double(year)) %>%
  mutate(beer_style=factor(beer_style))
  
ggplot(facted_hist_input, aes(year)) + 
  geom_bar()  + 
  facet_wrap(~fct_reorder(facted_hist_input$beer_style, facted_hist_input$rn))
```

```{r}
heatmap_input <- most_popular_beer_ratings %>%
  select(beer_style, beer_abv, beer_ibu, beer_average_rating, beer_num_ratings, year) %>%
  mutate(year=as.integer(year)) %>%
  drop_na() %>% 
  filter(beer_abv <= 20) %>%
  filter(beer_ibu <= 400)
  

GGally::ggparcoord(heatmap_input, 
                   columns=2:5, 
                   scale='uniminmax', 
                   alphaLines = 0.2, 
                   groupColumn = 1)
```

```{r}
facted_hist_input %>% 
  group_by(beer_style, year) %>%
  summarise(freq=n()) %>%
  ungroup() %>%
  ggplot(aes(year, freq)) +
  geom_line() +
  facet_wrap(~beer_style)
```

```{r}
cleaned_all_breweries <- all_breweries %>%
  filter(num_of_beers >= 10) %>%
  filter(!brewery_type %in% c("proprietor", "bar", "nano", "closed"))
```

```{r}
cleaned_all_breweries %>%
  group_by(state) %>%
  summarise(freq=n(), 
            state_mean_rating=mean(average_rating), 
            state_median_rating=median(average_rating), 
            state_mean_num_of_ratings=mean(num_of_ratings), 
            state_median_num_of_ratings=median(num_of_ratings)) %>%
  ungroup() %>%
  
  ggplot(aes(state_mean_rating, state_mean_num_of_ratings)) +
    geom_point()
```

```{r}
cleaned_all_breweries %>%
  group_by(state) %>%
  arrange(desc(average_rating)) %>%
  slice(1:2) %>%
  ungroup() %>%
  
ggplot(aes(x=average_rating, y=fct_reorder(state, average_rating, .fun=max))) +
  geom_point()
```

```{r}
state_political <- read_csv(paste(folder_path, 'states_politics.csv', sep='/'))
state_political
```

```{r}
state_all_breweries <- cleaned_all_breweries %>% left_join(y=state_political, by=c("state"))
state_all_breweries
```

```{r}
state_all_breweries %>%
  group_by(state, political_tendency) %>%
  summarise(
    freq = n(),
    state_mean_rating = mean(average_rating),
    state_num_of_ratings = mean(num_of_ratings)
  ) %>%
  ungroup() %>%
ggplot(aes(state_mean_rating, state_num_of_ratings)) +
  geom_point(aes(color = political_tendency)) +
  scale_color_manual(values = c(
    "Red" = "#FF4646",
    "Blue" = "#4176FB"))
```

### Geoplot

```{r}
coordinate_all_breweries <- cleaned_all_breweries %>%
  filter(!is.na(longitude) | !is.na(latitude)) %>%
  filter(!state %in% c('Alaska', 'Hawaii'))
```

```{r}
usa <- map_data('state')
ggplot() +
  geom_polygon(data = usa,
               aes(
                 x = long,
                 y = lat,
                 group = group,
                 fill = region,
                 color = 'white'
               )) +
  geom_point(
    data = coordinate_all_breweries,
    aes(x = longitude, y = latitude),
    color = "black",
    alpha = 0.1
  ) +
  guides(fill = "none") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  ggtitle('U.S. Map') +
  coord_fixed(1.3)
```

```{r}

# data frame must contain "region" and "value" columns
df_brewery_count <-
  cleaned_all_breweries %>% group_by(state) %>% summarise(no_of_breweries = n()) %>%
  transmute(region = tolower(`state`), value = no_of_breweries)

state_choropleth(df_brewery_count,
                 title = "No of Breweries per State in 2021",
                 legend = "count")
```

```{r}
average_brewery_rating <- cleaned_all_breweries %>%
  group_by(state) %>%
  summarise(average_rating_per_state = mean(average_rating)) %>%
  transmute(region = tolower(`state`), value = average_rating_per_state)

state_choropleth(average_brewery_rating,
                 title = "Average ratings per State in 2021",
                 legend = "Rating")
```

```{r}
us_temperatures <- read_csv(paste(folder_path, 'us_avg_temperature_by_state.csv', sep='/'))
us_temperatures
```

```{r}
temperature_all_beers <- cleaned_all_beers %>% left_join(y=us_temperatures, by=c("state"))
temperature_all_beers
```

```{r}
temperature_all_beers %>% 
  group_by(state, beer_style) %>%
  summarise(no_of_beer = n())
```
